#!/usr/bin/env bash
# Automatizing the nginx configuration into servers

./transfer 0-custom_http_response-header 34.75.91.155 ubuntu ~/.ssh/holberton
ssh ubuntu@34.75.91.155 -i ~/.ssh/holberton './0-custom_http_response-header'

./transfer 0-custom_http_response-header 34.75.91.155 ubuntu ~/.ssh/holberton
ssh ubuntu@35.196.131.244 -i ~/.ssh/holberton './0-custom_http_response-header'

./transfer 0-custom_http_response-header 34.75.91.155 ubuntu ~/.ssh/holberton
ssh ubuntu@35.185.65.161 -i ~/.ssh/holberton './0-custom_http_response-header'

curl -sI 34.75.91.155 | grep X-Served-By
curl -sI 35.196.131.244 | grep X-Served-By
curl -sI 35.185.65.161 | grep X-Served-By
