#!/usr/bin/env bash
# Display Fizz when number is multiple of 3, or Buzz when is multiple of 5
for i in {1..100}; do
	if ((i % 3 == 0 && i % 5 == 0)); then
		echo "FizzBuzz"
	elif ((i % 3 == 0)); then
		echo "Fizz"
	elif ((i % 5 == 0)); then
		echo "Buzz"
	else
		echo $i
	fi
done
