#!/usr/bin/env bash
# A script that used as an IP set up for working in docker
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
